var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                 o                xxx           ",
   "                                                           xx    xx!xx          ",
   "                                    o o          xx              x!!!x          ",
   "                                                                 xx!xx          ",
   "                    *              xxxxx                          xvx           ",
   "                                                                            xx  ",
   "  xx                                      o o                                x  ",
   "  x                                                                          x  ",
   "  x                                      xxxxx                             o x  ",
   "  x             x   ^^    ^   x                               ^              x  ",
   "  x  @          x             x                            x     xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx          x     xxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x          x           x     x                    ",
   "                              x!!!!!!!!!!x           x!!!!!x                    ",
   "                              x!!!!!!!!!!x           x!!!!!x                    ",
   "                              xxxxxxxxxxxx           xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxxxxxxxxx!!x         x                                               x!x  ",
   "                                                xx!x         x     o   o                                    xx!x  ",
   "                                                 x!x         x                                              xx!x  ",
   "                                                 xvx         x     x   x                                    xx!x  ",
   "                                                             xx  |   |   |  xx                          o * xx!x  ",
   "                                                              xx!!!!!!!!!!!xx xx                            x!!x  ",
   "                                                               xxxx!!!!!xxxx    x                    xxxxxxxx!!x  ",
   "                                                                  xxxxxxx                         xxxxxxxxxx!!!x  ",
   "                                                                                            xxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                            o  o                                                  ",
   "               xxxxxxx          x   xxx                                                                           ",
   "              xx     xx         x   x                      xxxxxx                                                 ",
   "             xx       xx        x o x          *                                                                  ",
   "     @       x         x        x   x                                               *                             ",
   "    xxx      x         x        x   x     ^    x     x                                                            ",
   "    x x      x         x       xx o xx         xx    x                                                            ",
   "!!!!x x!!!!!!x         x      xx     xxxxxxxxxxx     x!!!!!!!!!!                                                  ",
   "!!!!x x!!!!!!x         x     xx                      x!!!!!!!xx!         xxxxxxxxxxxxxxxxxxxxx  o o  xx           ",
   "!!!!x x!!!!!!x         x     x    o                 xx!!!!!!xx !                             xx     xx            ",
   "!!!!x x!!!!!!x         x     xxxxxxxxxxxxxxxxxxxxxxxx!!!!!!xx  !                              xxxxxxx             ",
   "!!!!x x!!!!!!x         x                         *  !!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x                            !!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                            o      o                                          ",
   "                                                                                                              ",
   "                              o   o   o   o                xx     xx                                          ",
   "                                                                                                              ",
   "                             xxx xxx xxx xxx          x!!!!!!!!!!!!!!x                                        ",
   "                             x xxx x x xxx x          x!!!!!!!v!!!!!!x                                        ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                 *                                                                                      x  ",
   "  x                                        *                             o                                 x  ",
   "  x                                                                                                        x  ",
   "  x                xxx             o o    xxx                            x         xxx                     x  ",
   "  x               xxxxx                   x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo            xxx    x                             x x        xxx     o    xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx     ^         ^         ^  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
